var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,k){a!=Array.prototype&&a!=Object.prototype&&(a[d]=k.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var k=0,h={next:function(){if(k<a.length){var l=k++;return{value:d(l,a[l]),done:!1}}h.next=function(){return{done:!0,value:void 0}};return h.next()}};h[Symbol.iterator]=function(){return h};return h};
$jscomp.polyfill=function(a,d,k,h){if(d){k=$jscomp.global;a=a.split(".");for(h=0;h<a.length-1;h++){var l=a[h];l in k||(k[l]={});k=k[l]}a=a[a.length-1];h=k[a];d=d(h);d!=h&&null!=d&&$jscomp.defineProperty(k,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a,d,k,h,l,v){function p(a,b){var e={};q(e,b.constants);Object.keys(a).forEach(function(c){var g=n(b.properties,c);e[g]=a[c]});return e}function t(a,b,c,d){for(var e=0;e<b.length;e++){var r=b[e];Object.keys(b[e]).forEach(function(b){var e=n(c.properties,b);b=r[b];e=d+"_"+e;m(a[e])?a[e]=a[e]+","+b:a[e]=b})}}function q(a,b,c){b=void 0===b?{}:b;c=void 0===c?"facebook":c;Object.keys(b).forEach(function(e){e=b[e];m(e.externalName)&&m(e.externalName[c])&&(a[e.externalName[c]]=e._const)})}function n(a,
b,c){c=void 0===c?"facebook":c;var e=b;m(a[b])&&m(a[b].externalName)&&m(a[b].externalName[c])&&(e=a[b].externalName[c]);return e}function m(a){return"undefined"!==typeof a&&null!==a}!function(a,b,c,d,g,f,h){a.fbq||(g=a.fbq=function(){g.callMethod?g.callMethod.apply(g,arguments):g.queue.push(arguments)},a._fbq||(a._fbq=g),g.push=g,g.loaded=!0,g.version="2.0",g.queue=[],f=b.createElement(c),f.async=!0,f.src=d,h=b.getElementsByTagName(c)[0],h.parentNode.insertBefore(f,h))}(window,document,"script","https://connect.facebook.net/en_US/fbevents.js");
var f=a.tenmax_facebook_q,u=function(a,b){b=void 0===b?{}:b;var e=f.config.schema.events[a],d=f.config.schema.definitions.content,g={};q(g,e.constants);Object.keys(b).forEach(function(a){var c=b[a],f=n(e.properties,a);if("content"===a){g.content_ids=c.id;var h=p(c,d);Object.keys(h).forEach(function(a){g[a]=h[a]})}else"contents"===a?(a=c||[],g.content_ids=a.map(function(a){return a.id}),g[f]=[],g[f]=a.map(function(a){return p(a,d)}),t(g,a,d,f)):g[f]=c});return g};f.callMethod=function(a){var b=Array.prototype.slice.call(a),
c=b.shift();a=b.shift();b=b.shift()||{};switch(c){case "init":for(a=0;a<f.config.pixels.length;a++)console.log("fbq('init', "+f.config.pixels[a]+", "+JSON.stringify(b)+");"),fbq("init",f.config.pixels[a],b);break;case "track":for(c=n(f.config.schema.events,a),a=u(a,b),b=0;b<f.config.pixels.length;b++)switch(c){case "AddPaymentInfo":case "AddToCart":case "AddToWishlist":case "CompleteRegistration":case "Contact":case "CustomizeProduct":case "Donate":case "FindLocation":case "InitiateCheckout":case "Lead":case "PageView":case "Purchase":case "Schedule":case "Search":case "StartTrial":case "SubmitApplication":case "Subscribe":case "ViewContent":console.log("fbq('trackSingle', "+
f.config.pixels[b]+", "+c+", "+JSON.stringify(a)+");");fbq("trackSingle",f.config.pixels[b],c,a);break;default:console.log("fbq('trackSingleCustom', "+f.config.pixels[b]+", "+c+", "+JSON.stringify(a)+");"),fbq("trackSingleCustom",f.config.pixels[b],c,a)}}};a=f.queue.slice();for(d=0;d<a.length;d++)f.callMethod.apply(f,a[d])})(window,document);
