var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,f){a!=Array.prototype&&a!=Object.prototype&&(a[b]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var f=0,d={next:function(){if(f<a.length){var h=f++;return{value:b(h,a[h]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,b,f,d){if(b){f=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var h=a[d];h in f||(f[h]={});f=f[h]}a=a[a.length-1];d=f[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
(function(a,b,f,d,h,q){function l(a,c){var e={};k(e,c.constants);Object.keys(a).forEach(function(c){e[c]=a[c]});return e}function n(a,c,e,b){for(e=0;e<c.length;e++){var m=c[e];Object.keys(c[e]).forEach(function(c){var e=m[c];c=b+"_"+c;var d=a[c];"undefined"!==typeof d&&null!==d?a[c]=a[c]+","+e:a[c]=e})}}function k(a,c){c=void 0===c?{}:c;Object.keys(c).forEach(function(e){var b=c[e];0!==e.indexOf("_",0)&&(a[e]=b._const)})}var g=a.tenmax_tenmax_q;(function(a,c,e,b,d,f){a.cq||(b=a.cq=function(){b.callMethod?
b.callMethod.apply(b,arguments):b.queue.push(arguments)},b.config=g.config,b.queue=[],b.callMethods=[],d=c.createElement("script"),f=c.getElementsByTagName("script")[0],d.async=!0,d.src=g.config.wbJsUrl,f.parentNode.insertBefore(d,f))})(window,document,"script","cq");var p=function(a,c){c=void 0===c?{}:c;var b=g.config.schema.definitions.content,d={};k(d,g.config.schema.events[a].constants);Object.keys(c).forEach(function(a){var e=c[a];if("content"===a){var f=e||{};Object.keys(f).forEach(function(a){d[a]=
f[a]})}else"contents"===a?(e=e||[],d[a]=e.map(function(a){return l(a,b)}),n(d,e,b,a)):d[a]=e});return d};g.callMethod=function(a){var c=Array.prototype.slice.call(a),b=c.shift();a=c.shift();c=c.shift();switch(b){case "init":console.log("cq('init', "+g.config.pixels[0]+", "+JSON.stringify(c)+");");cq("init",g.config.pixels[0],c);break;case "track":a&&(b=p(a,c),console.log("cq('track', "+a+", "+JSON.stringify(b)+");"),cq("track",a,b))}};a=g.queue.slice();for(b=0;b<a.length;b++)g.callMethod.apply(g,
a[b])})(window,document);
